#version 450
layout(local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

layout(set = 0, binding = 0, std140) uniform support_buffer
{
    uint _m0;
    uint _m1[8];
    vec4 _m2;
    vec4 _m3;
    int _m4;
    float _m5[73];
    ivec4 _m6;
    int _m7;
} support_buffer_1;

layout(set = 0, binding = 1, std140) uniform vb_info
{
    uvec4 _m0;
    uvec4 _m1;
    uvec4 _m2[32];
    uvec4 _m3[32];
} vb_info_1;

layout(set = 0, binding = 2, std140) uniform vp_c0
{
    vec4 _m0[4096];
} vp_c0_1;

layout(set = 1, binding = 0, std430) buffer vertex_output
{
    float _m0[];
} vertex_output_1;

layout(set = 1, binding = 3, std430) buffer vp_s0
{
    uint _m0[];
} vp_s0_1;

layout(set = 2, binding = 0) uniform samplerBuffer ib_data;
layout(set = 2, binding = 5) uniform samplerBuffer vb_data3;

void main()
{
    return;
}